import type { PosterTemplate } from "./types";

export const POSTER_TEMPLATES: PosterTemplate[] = [
  {
    id: "festival",
    name: "Festival Greeting",
    category: "festival",
    emoji: "🎉",
    canvasSize: { width: 1080, height: 1080 },
    defaultPrompt:
      "colorful festive Indian celebration background with diyas lights flowers rangoli vibrant colors",
    gradient: "from-orange-500 to-red-600",
    textObjects: [
      {
        text: "Happy Festival!",
        fontFamily: "Poppins",
        fontSize: 80,
        fill: "#ffffff",
        fontWeight: "bold",
        textAlign: "center",
        left: 540,
        top: 400,
      },
      {
        text: "Wishing you joy and prosperity",
        fontFamily: "Poppins",
        fontSize: 40,
        fill: "#ffe082",
        fontWeight: "normal",
        textAlign: "center",
        left: 540,
        top: 520,
      },
    ],
  },
  {
    id: "event",
    name: "Event Invitation",
    category: "event",
    emoji: "📬",
    canvasSize: { width: 1080, height: 1350 },
    defaultPrompt:
      "elegant dark luxury event invitation background with subtle gold geometric patterns bokeh lights",
    gradient: "from-purple-600 to-indigo-700",
    textObjects: [
      {
        text: "You're Invited",
        fontFamily: "Playfair Display",
        fontSize: 90,
        fill: "#f5c518",
        fontWeight: "bold",
        textAlign: "center",
        left: 540,
        top: 300,
      },
      {
        text: "Event Name Here",
        fontFamily: "Poppins",
        fontSize: 50,
        fill: "#ffffff",
        fontWeight: "normal",
        textAlign: "center",
        left: 540,
        top: 450,
      },
      {
        text: "Date • Time • Venue",
        fontFamily: "Poppins",
        fontSize: 36,
        fill: "#cccccc",
        fontWeight: "normal",
        textAlign: "center",
        left: 540,
        top: 560,
      },
    ],
  },
  {
    id: "sale",
    name: "Sale / Offer",
    category: "business",
    emoji: "🛍️",
    canvasSize: { width: 1080, height: 1080 },
    defaultPrompt:
      "vibrant dynamic sale promotional background with bold colors ribbons confetti shopping theme",
    gradient: "from-yellow-400 to-orange-500",
    textObjects: [
      {
        text: "BIG SALE",
        fontFamily: "Poppins",
        fontSize: 120,
        fill: "#ffffff",
        fontWeight: "bold",
        textAlign: "center",
        left: 540,
        top: 300,
      },
      {
        text: "UP TO 50% OFF",
        fontFamily: "Poppins",
        fontSize: 60,
        fill: "#1a1a1a",
        fontWeight: "bold",
        textAlign: "center",
        left: 540,
        top: 480,
      },
    ],
  },
  {
    id: "birthday",
    name: "Birthday",
    category: "celebration",
    emoji: "🎂",
    canvasSize: { width: 1080, height: 1080 },
    defaultPrompt:
      "happy birthday celebration background with colorful balloons confetti streamers cake candles pastel colors",
    gradient: "from-pink-500 to-rose-600",
    textObjects: [
      {
        text: "Happy Birthday!",
        fontFamily: "Poppins",
        fontSize: 85,
        fill: "#ffffff",
        fontWeight: "bold",
        textAlign: "center",
        left: 540,
        top: 380,
      },
      {
        text: "Name Here",
        fontFamily: "Poppins",
        fontSize: 55,
        fill: "#ffe0f0",
        fontWeight: "normal",
        textAlign: "center",
        left: 540,
        top: 510,
      },
    ],
  },
  {
    id: "motivational",
    name: "Motivational Quote",
    category: "social",
    emoji: "💬",
    canvasSize: { width: 1080, height: 1080 },
    defaultPrompt:
      "minimalist inspirational background with soft gradient sunrise mountains abstract calm professional",
    gradient: "from-cyan-500 to-blue-600",
    textObjects: [
      {
        text: '"Your quote here"',
        fontFamily: "Playfair Display",
        fontSize: 72,
        fill: "#ffffff",
        fontStyle: "italic",
        textAlign: "center",
        left: 540,
        top: 380,
      },
      {
        text: "— Author",
        fontFamily: "Poppins",
        fontSize: 36,
        fill: "#cccccc",
        fontWeight: "normal",
        textAlign: "center",
        left: 540,
        top: 550,
      },
    ],
  },
  {
    id: "blank",
    name: "Blank Canvas",
    category: "custom",
    emoji: "🎨",
    canvasSize: { width: 1080, height: 1080 },
    defaultPrompt: "abstract minimalist gradient background smooth colors artistic",
    gradient: "from-gray-600 to-zinc-700",
    textObjects: [],
  },
];
